import { Clock } from 'phosphor-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

interface ExamConceptProps {
  studentIdCode: string;
  school: string;
  examDate: string;
  examTime: string;
  examType: string;
}

export default function ExamConcept({
  studentIdCode,
  school,
  examDate,
  examTime,
  examType,
}: ExamConceptProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
  };

  return (
    <Card className="bg-blue-50 border-blue-200">
      <CardHeader>
        <CardTitle className="text-lg">How PIN-Based Authentication Works</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4 text-sm">
        <p>
          This system demonstrates an innovative approach to exam authentication. Since we already know several key pieces of information about you and the exam, we can validate your identity through a secure PIN-based system.
        </p>
        
        <div className="space-y-3">
          <div>
            <p className="font-semibold text-blue-900 mb-1">What We Know:</p>
            <ul className="list-disc list-inside space-y-1 text-blue-800 ml-2">
              <li>You registered for this exam in advance</li>
              <li>Your confirmed student ID (Isikukood: {studentIdCode})</li>
              <li>The school where the exam takes place ({school.replace('-', ' ')})</li>
              <li>The exam's scheduled time ({formatDate(examDate)} at {examTime})</li>
              <li>The type of exam ({examType.replace('-', ' ')})</li>
            </ul>
          </div>

          <div>
            <p className="font-semibold text-blue-900 mb-1">How It Works:</p>
            <ol className="list-decimal list-inside space-y-1 text-blue-800 ml-2">
              <li>Your unique PIN is generated by hashing your public student data and exam information</li>
              <li>The PIN is created using your Isikukood, exam date, and ID card document digits</li>
              <li>To access the exam, you simply validate using this PIN</li>
              <li>The system matches your exam details with your PIN to grant access</li>
              <li>Once the exam is completed, all hashes are deleted for privacy</li>
            </ol>
          </div>

          <div className="bg-white p-3 rounded border border-blue-300">
            <p className="text-xs text-blue-900">
              <strong>Note:</strong> This validates that you are the correct student at the correct location and time, without requiring traditional computer login procedures during the exam.
            </p>
          </div>

          <div className="bg-green-50 border border-green-200 p-3 rounded flex gap-2">
            <Clock size={16} weight="regular" className="text-green-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-xs font-semibold text-green-900 mb-1">Production Feature: Time Window Validation</p>
              <p className="text-xs text-green-800">
                In the production system, students can only access exams within a specific time window. 
                For example, access is granted from 15 minutes before the scheduled start time until 
                30 minutes after. This prevents unauthorized exam access outside the designated time period.
              </p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

